-- MySQL Script generated by MySQL Workbench
-- Sat Dec  7 09:00:37 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BibliotecaMusical
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BibliotecaMusical
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BibliotecaMusical` DEFAULT CHARACTER SET utf8 ;
USE `BibliotecaMusical` ;

-- -----------------------------------------------------
-- Table `BibliotecaMusical`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BibliotecaMusical`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(45) NOT NULL,
  `nombreUsuario` VARCHAR(45) NOT NULL,
  `contrasenna` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `edad` INT NULL DEFAULT NULL,
  `pais` VARCHAR(45) NULL DEFAULT NULL,
  `cedula` INT NULL DEFAULT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BibliotecaMusical`.`listareproduccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BibliotecaMusical`.`listareproduccion` (
  `idlistareproducciones` INT NOT NULL AUTO_INCREMENT,
  `fechaCreacion` DATE NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `calificacion` DOUBLE NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idlistareproducciones`, `usuario_idusuario`),
  INDEX `fk_listareproduccion_usuario_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_listareproduccion_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `BibliotecaMusical`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BibliotecaMusical`.`cancion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BibliotecaMusical`.`cancion` (
  `idcancion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `pathCancion` VARCHAR(300) NOT NULL,
  `fechaLanzamiento` DATE NOT NULL,
  `calificacion` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `compositor` VARCHAR(45) NOT NULL,
  `artista` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcancion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BibliotecaMusical`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BibliotecaMusical`.`album` (
  `idalbum` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `fechaLanzamiento` DATE NOT NULL,
  `imagen` VARCHAR(45) NOT NULL,
  `canciones` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idalbum`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BibliotecaMusical`.`artista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BibliotecaMusical`.`artista` (
  `idartista` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `nombreArtistico` VARCHAR(45) NOT NULL,
  `fechaNacimiento` DATE NOT NULL,
  `fechaDefuncion` DATE NULL,
  `pais` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  `edad` INT NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idartista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BibliotecaMusical`.`listareproduccion_has_cancion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BibliotecaMusical`.`listareproduccion_has_cancion` (
  `listareproduccion_idlistareproducciones` INT NOT NULL,
  `listareproduccion_usuario_idusuario` INT NOT NULL,
  `cancion_idcancion` INT NOT NULL,
  PRIMARY KEY (`listareproduccion_idlistareproducciones`, `listareproduccion_usuario_idusuario`, `cancion_idcancion`),
  INDEX `fk_listareproduccion_has_cancion_cancion1_idx` (`cancion_idcancion` ASC) VISIBLE,
  INDEX `fk_listareproduccion_has_cancion_listareproduccion1_idx` (`listareproduccion_idlistareproducciones` ASC, `listareproduccion_usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_listareproduccion_has_cancion_listareproduccion1`
    FOREIGN KEY (`listareproduccion_idlistareproducciones` , `listareproduccion_usuario_idusuario`)
    REFERENCES `BibliotecaMusical`.`listareproduccion` (`idlistareproducciones` , `usuario_idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_listareproduccion_has_cancion_cancion1`
    FOREIGN KEY (`cancion_idcancion`)
    REFERENCES `BibliotecaMusical`.`cancion` (`idcancion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BibliotecaMusical`.`compositor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BibliotecaMusical`.`compositor` (
  `idcompositor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `edad` INT NOT NULL,
  `generos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcompositor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BibliotecaMusical`.`usuario_has_cancion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BibliotecaMusical`.`usuario_has_cancion` (
  `usuario_idusuario` INT NOT NULL,
  `cancion_idcancion` INT NOT NULL,
  PRIMARY KEY (`usuario_idusuario`, `cancion_idcancion`),
  INDEX `fk_usuario_has_cancion_cancion1_idx` (`cancion_idcancion` ASC) VISIBLE,
  INDEX `fk_usuario_has_cancion_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_cancion_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `BibliotecaMusical`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_cancion_cancion1`
    FOREIGN KEY (`cancion_idcancion`)
    REFERENCES `BibliotecaMusical`.`cancion` (`idcancion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BibliotecaMusical`.`album_has_cancion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BibliotecaMusical`.`album_has_cancion` (
  `album_idalbum` INT NOT NULL,
  `cancion_idcancion` INT NOT NULL,
  PRIMARY KEY (`album_idalbum`, `cancion_idcancion`),
  INDEX `fk_album_has_cancion_cancion1_idx` (`cancion_idcancion` ASC) VISIBLE,
  INDEX `fk_album_has_cancion_album1_idx` (`album_idalbum` ASC) VISIBLE,
  CONSTRAINT `fk_album_has_cancion_album1`
    FOREIGN KEY (`album_idalbum`)
    REFERENCES `BibliotecaMusical`.`album` (`idalbum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_album_has_cancion_cancion1`
    FOREIGN KEY (`cancion_idcancion`)
    REFERENCES `BibliotecaMusical`.`cancion` (`idcancion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BibliotecaMusical`.`genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BibliotecaMusical`.`genero` (
  `idgenero` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idgenero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BibliotecaMusical`.`compositor_has_genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BibliotecaMusical`.`compositor_has_genero` (
  `compositor_idcompositor` INT NOT NULL,
  `genero_idgenero` INT NOT NULL,
  PRIMARY KEY (`compositor_idcompositor`, `genero_idgenero`),
  INDEX `fk_compositor_has_genero_genero1_idx` (`genero_idgenero` ASC) VISIBLE,
  INDEX `fk_compositor_has_genero_compositor1_idx` (`compositor_idcompositor` ASC) VISIBLE,
  CONSTRAINT `fk_compositor_has_genero_compositor1`
    FOREIGN KEY (`compositor_idcompositor`)
    REFERENCES `BibliotecaMusical`.`compositor` (`idcompositor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compositor_has_genero_genero1`
    FOREIGN KEY (`genero_idgenero`)
    REFERENCES `BibliotecaMusical`.`genero` (`idgenero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
